#!/usr/bin/env perl

use warnings;
use strict;

our $VERSION = '$Id$';

undef $/;
my $in = <STDIN>;
while( @ARGV ) {
    my $prog   = shift;
    my $marker = '%%' . uc( $prog ) . '%%';

    my $help = qx(./$prog -h);
    $in =~ s/^$marker\n/$help/m;
}
print( $in );

__END__

=pod

=cut
